package com.smartearthen.model;

public enum AlertType {
    TEMPERATURE_HIGH, TEMPERATURE_LOW, HUMIDITY_CRITICAL, HUMIDITY_HIGH,
    CO2_HIGH, BATTERY_LOW, SENSOR_OFFLINE, ANOMALY_AI, STRUCTURAL, MATERIAL_MOISTURE
}
